[project]
name = "pixieai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "duckduckgo-search>=8.1.1",
    "mlx-lm>=0.29.1",
    "pyside6>=6.10.1",
]
